version: "3.9"

services:
  devcont:
    build:
      dockerfile: .devcontainer/Dockerfile
      context: .
    volumes:
      - ./:/AzureTRE/
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -F /dev/null
